namespace SharpMC.Enchantments
{
    public static class KnownEnchantments
    {
        public static readonly Enchantment AquaAffinity = new Enchantment { Id = 6, DisplayName = "Aqua Affinity", Name = "aqua_affinity", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorHead };
        public static readonly Enchantment BaneOfArthropods = new Enchantment { Id = 14, DisplayName = "Bane of Arthropods", Name = "bane_of_arthropods", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon , Exclude = new [] { "sharpness", "smite" } };
        public static readonly Enchantment BindingCurse = new Enchantment { Id = 10, DisplayName = "Curse of Binding", Name = "binding_curse", MaxLevel = 1, TreasureOnly = true, Curse = true, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.Wearable };
        public static readonly Enchantment BlastProtection = new Enchantment { Id = 3, DisplayName = "Blast Protection", Name = "blast_protection", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Armor , Exclude = new [] { "protection", "fire_protection", "projectile_protection" } };
        public static readonly Enchantment Channeling = new Enchantment { Id = 32, DisplayName = "Channeling", Name = "channeling", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.Trident , Exclude = new [] { "riptide" } };
        public static readonly Enchantment DepthStrider = new Enchantment { Id = 8, DisplayName = "Depth Strider", Name = "depth_strider", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorFeet , Exclude = new [] { "frost_walker" } };
        public static readonly Enchantment Efficiency = new Enchantment { Id = 19, DisplayName = "Efficiency", Name = "efficiency", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 10, Tradeable = true, Discoverable = true, Category = EnchantCategory.Digger };
        public static readonly Enchantment FeatherFalling = new Enchantment { Id = 2, DisplayName = "Feather Falling", Name = "feather_falling", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorFeet };
        public static readonly Enchantment FireAspect = new Enchantment { Id = 16, DisplayName = "Fire Aspect", Name = "fire_aspect", MaxLevel = 2, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon };
        public static readonly Enchantment FireProtection = new Enchantment { Id = 1, DisplayName = "Fire Protection", Name = "fire_protection", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Armor , Exclude = new [] { "protection", "blast_protection", "projectile_protection" } };
        public static readonly Enchantment Flame = new Enchantment { Id = 25, DisplayName = "Flame", Name = "flame", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Bow };
        public static readonly Enchantment Fortune = new Enchantment { Id = 22, DisplayName = "Fortune", Name = "fortune", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Digger , Exclude = new [] { "silk_touch" } };
        public static readonly Enchantment FrostWalker = new Enchantment { Id = 9, DisplayName = "Frost Walker", Name = "frost_walker", MaxLevel = 2, TreasureOnly = true, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorFeet , Exclude = new [] { "depth_strider" } };
        public static readonly Enchantment Impaling = new Enchantment { Id = 30, DisplayName = "Impaling", Name = "impaling", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Trident };
        public static readonly Enchantment Infinity = new Enchantment { Id = 26, DisplayName = "Infinity", Name = "infinity", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.Bow , Exclude = new [] { "mending" } };
        public static readonly Enchantment Knockback = new Enchantment { Id = 15, DisplayName = "Knockback", Name = "knockback", MaxLevel = 2, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon };
        public static readonly Enchantment Looting = new Enchantment { Id = 17, DisplayName = "Looting", Name = "looting", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon , Exclude = new [] { "silk_touch" } };
        public static readonly Enchantment Loyalty = new Enchantment { Id = 29, DisplayName = "Loyalty", Name = "loyalty", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Trident , Exclude = new [] { "riptide" } };
        public static readonly Enchantment LuckOfTheSea = new Enchantment { Id = 27, DisplayName = "Luck of the Sea", Name = "luck_of_the_sea", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.FishingRod , Exclude = new [] { "silk_touch" } };
        public static readonly Enchantment Lure = new Enchantment { Id = 28, DisplayName = "Lure", Name = "lure", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.FishingRod };
        public static readonly Enchantment Mending = new Enchantment { Id = 36, DisplayName = "Mending", Name = "mending", MaxLevel = 1, TreasureOnly = true, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Breakable , Exclude = new [] { "infinity" } };
        public static readonly Enchantment Multishot = new Enchantment { Id = 33, DisplayName = "Multishot", Name = "multishot", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Crossbow , Exclude = new [] { "piercing" } };
        public static readonly Enchantment Piercing = new Enchantment { Id = 35, DisplayName = "Piercing", Name = "piercing", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 10, Tradeable = true, Discoverable = true, Category = EnchantCategory.Crossbow , Exclude = new [] { "multishot" } };
        public static readonly Enchantment Power = new Enchantment { Id = 23, DisplayName = "Power", Name = "power", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 10, Tradeable = true, Discoverable = true, Category = EnchantCategory.Bow };
        public static readonly Enchantment ProjectileProtection = new Enchantment { Id = 4, DisplayName = "Projectile Protection", Name = "projectile_protection", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Armor , Exclude = new [] { "protection", "fire_protection", "blast_protection" } };
        public static readonly Enchantment Protection = new Enchantment { Id = 0, DisplayName = "Protection", Name = "protection", MaxLevel = 4, TreasureOnly = false, Curse = false, Weight = 10, Tradeable = true, Discoverable = true, Category = EnchantCategory.Armor , Exclude = new [] { "fire_protection", "blast_protection", "projectile_protection" } };
        public static readonly Enchantment Punch = new Enchantment { Id = 24, DisplayName = "Punch", Name = "punch", MaxLevel = 2, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Bow };
        public static readonly Enchantment QuickCharge = new Enchantment { Id = 34, DisplayName = "Quick Charge", Name = "quick_charge", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Crossbow };
        public static readonly Enchantment Respiration = new Enchantment { Id = 5, DisplayName = "Respiration", Name = "respiration", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorHead };
        public static readonly Enchantment Riptide = new Enchantment { Id = 31, DisplayName = "Riptide", Name = "riptide", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Trident , Exclude = new [] { "loyalty", "channeling" } };
        public static readonly Enchantment Sharpness = new Enchantment { Id = 12, DisplayName = "Sharpness", Name = "sharpness", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 10, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon , Exclude = new [] { "smite", "bane_of_arthropods" } };
        public static readonly Enchantment SilkTouch = new Enchantment { Id = 20, DisplayName = "Silk Touch", Name = "silk_touch", MaxLevel = 1, TreasureOnly = false, Curse = false, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.Digger , Exclude = new [] { "looting", "fortune", "luck_of_the_sea" } };
        public static readonly Enchantment Smite = new Enchantment { Id = 13, DisplayName = "Smite", Name = "smite", MaxLevel = 5, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon , Exclude = new [] { "sharpness", "bane_of_arthropods" } };
        public static readonly Enchantment SoulSpeed = new Enchantment { Id = 11, DisplayName = "Soul Speed", Name = "soul_speed", MaxLevel = 3, TreasureOnly = true, Curse = false, Weight = 1, Tradeable = false, Discoverable = false, Category = EnchantCategory.ArmorFeet };
        public static readonly Enchantment Sweeping = new Enchantment { Id = 18, DisplayName = "Sweeping Edge", Name = "sweeping", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 2, Tradeable = true, Discoverable = true, Category = EnchantCategory.Weapon };
        public static readonly Enchantment Thorns = new Enchantment { Id = 7, DisplayName = "Thorns", Name = "thorns", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.ArmorChest };
        public static readonly Enchantment Unbreaking = new Enchantment { Id = 21, DisplayName = "Unbreaking", Name = "unbreaking", MaxLevel = 3, TreasureOnly = false, Curse = false, Weight = 5, Tradeable = true, Discoverable = true, Category = EnchantCategory.Breakable };
        public static readonly Enchantment VanishingCurse = new Enchantment { Id = 37, DisplayName = "Curse of Vanishing", Name = "vanishing_curse", MaxLevel = 1, TreasureOnly = true, Curse = true, Weight = 1, Tradeable = true, Discoverable = true, Category = EnchantCategory.Vanishable };
        
        public static readonly Enchantment[] All = { AquaAffinity, BaneOfArthropods, BindingCurse, BlastProtection, Channeling, DepthStrider, Efficiency, FeatherFalling, FireAspect, FireProtection, Flame, Fortune, FrostWalker, Impaling, Infinity, Knockback, Looting, Loyalty, LuckOfTheSea, Lure, Mending, Multishot, Piercing, Power, ProjectileProtection, Protection, Punch, QuickCharge, Respiration, Riptide, Sharpness, SilkTouch, Smite, SoulSpeed, Sweeping, Thorns, Unbreaking, VanishingCurse };
    }
}