namespace SharpMC.Foods
{
    public static class KnownFoods
    {
        public static readonly Food Apple = new Food { Id = 681, DisplayName = "Apple", Name = "apple", StackSize = 64, FoodPoints = 4, Saturation = 2.4, EffectiveQuality = 6.4, SaturationRatio = 0.6 };
        public static readonly Food BakedPotato = new Food { Id = 949, DisplayName = "Baked Potato", Name = "baked_potato", StackSize = 64, FoodPoints = 5, Saturation = 6, EffectiveQuality = 11, SaturationRatio = 1.2 };
        public static readonly Food Beef = new Food { Id = 853, DisplayName = "Raw Beef", Name = "beef", StackSize = 64, FoodPoints = 3, Saturation = 1.8000001, EffectiveQuality = 4.8, SaturationRatio = 0.6 };
        public static readonly Food Beetroot = new Food { Id = 1001, DisplayName = "Beetroot", Name = "beetroot", StackSize = 64, FoodPoints = 1, Saturation = 1.2, EffectiveQuality = 2.2, SaturationRatio = 1.2 };
        public static readonly Food BeetrootSoup = new Food { Id = 1003, DisplayName = "Beetroot Soup", Name = "beetroot_soup", StackSize = 1, FoodPoints = 6, Saturation = 7.2000003, EffectiveQuality = 13.200001, SaturationRatio = 1.2 };
        public static readonly Food Bread = new Food { Id = 737, DisplayName = "Bread", Name = "bread", StackSize = 64, FoodPoints = 5, Saturation = 6, EffectiveQuality = 11, SaturationRatio = 1.2 };
        public static readonly Food Carrot = new Food { Id = 947, DisplayName = "Carrot", Name = "carrot", StackSize = 64, FoodPoints = 3, Saturation = 3.6000001, EffectiveQuality = 6.6000004, SaturationRatio = 1.2 };
        public static readonly Food Chicken = new Food { Id = 855, DisplayName = "Raw Chicken", Name = "chicken", StackSize = 64, FoodPoints = 2, Saturation = 1.2, EffectiveQuality = 3.2, SaturationRatio = 0.6 };
        public static readonly Food ChorusFruit = new Food { Id = 999, DisplayName = "Chorus Fruit", Name = "chorus_fruit", StackSize = 64, FoodPoints = 4, Saturation = 2.4, EffectiveQuality = 6.4, SaturationRatio = 0.6 };
        public static readonly Food Cod = new Food { Id = 801, DisplayName = "Raw Cod", Name = "cod", StackSize = 64, FoodPoints = 2, Saturation = 0.4, EffectiveQuality = 2.4, SaturationRatio = 0.2 };
        public static readonly Food CookedBeef = new Food { Id = 854, DisplayName = "Steak", Name = "cooked_beef", StackSize = 64, FoodPoints = 8, Saturation = 12.8, EffectiveQuality = 20.8, SaturationRatio = 1.6 };
        public static readonly Food CookedChicken = new Food { Id = 856, DisplayName = "Cooked Chicken", Name = "cooked_chicken", StackSize = 64, FoodPoints = 6, Saturation = 7.2000003, EffectiveQuality = 13.200001, SaturationRatio = 1.2 };
        public static readonly Food CookedCod = new Food { Id = 805, DisplayName = "Cooked Cod", Name = "cooked_cod", StackSize = 64, FoodPoints = 5, Saturation = 6, EffectiveQuality = 11, SaturationRatio = 1.2 };
        public static readonly Food CookedMutton = new Food { Id = 981, DisplayName = "Cooked Mutton", Name = "cooked_mutton", StackSize = 64, FoodPoints = 6, Saturation = 9.6, EffectiveQuality = 15.6, SaturationRatio = 1.6 };
        public static readonly Food CookedPorkchop = new Food { Id = 764, DisplayName = "Cooked Porkchop", Name = "cooked_porkchop", StackSize = 64, FoodPoints = 8, Saturation = 12.8, EffectiveQuality = 20.8, SaturationRatio = 1.6 };
        public static readonly Food CookedRabbit = new Food { Id = 968, DisplayName = "Cooked Rabbit", Name = "cooked_rabbit", StackSize = 64, FoodPoints = 5, Saturation = 6, EffectiveQuality = 11, SaturationRatio = 1.2 };
        public static readonly Food CookedSalmon = new Food { Id = 806, DisplayName = "Cooked Salmon", Name = "cooked_salmon", StackSize = 64, FoodPoints = 6, Saturation = 9.6, EffectiveQuality = 15.6, SaturationRatio = 1.6 };
        public static readonly Food Cookie = new Food { Id = 846, DisplayName = "Cookie", Name = "cookie", StackSize = 64, FoodPoints = 2, Saturation = 0.4, EffectiveQuality = 2.4, SaturationRatio = 0.2 };
        public static readonly Food DriedKelp = new Food { Id = 850, DisplayName = "Dried Kelp", Name = "dried_kelp", StackSize = 64, FoodPoints = 1, Saturation = 0.6, EffectiveQuality = 1.6, SaturationRatio = 0.6 };
        public static readonly Food EnchantedGoldenApple = new Food { Id = 767, DisplayName = "Enchanted Golden Apple", Name = "enchanted_golden_apple", StackSize = 64, FoodPoints = 4, Saturation = 9.6, EffectiveQuality = 13.6, SaturationRatio = 2.4 };
        public static readonly Food GlowBerries = new Food { Id = 1054, DisplayName = "Glow Berries", Name = "glow_berries", StackSize = 64, FoodPoints = 2, Saturation = 0.4, EffectiveQuality = 2.4, SaturationRatio = 0.2 };
        public static readonly Food GoldenApple = new Food { Id = 766, DisplayName = "Golden Apple", Name = "golden_apple", StackSize = 64, FoodPoints = 4, Saturation = 9.6, EffectiveQuality = 13.6, SaturationRatio = 2.4 };
        public static readonly Food GoldenCarrot = new Food { Id = 952, DisplayName = "Golden Carrot", Name = "golden_carrot", StackSize = 64, FoodPoints = 6, Saturation = 14.400001, EffectiveQuality = 20.400002, SaturationRatio = 2.4 };
        public static readonly Food HoneyBottle = new Food { Id = 1061, DisplayName = "Honey Bottle", Name = "honey_bottle", StackSize = 16, FoodPoints = 6, Saturation = 1.2, EffectiveQuality = 7.2, SaturationRatio = 0.2 };
        public static readonly Food MelonSlice = new Food { Id = 849, DisplayName = "Melon Slice", Name = "melon_slice", StackSize = 64, FoodPoints = 2, Saturation = 1.2, EffectiveQuality = 3.2, SaturationRatio = 0.6 };
        public static readonly Food MushroomStew = new Food { Id = 731, DisplayName = "Mushroom Stew", Name = "mushroom_stew", StackSize = 1, FoodPoints = 6, Saturation = 7.2000003, EffectiveQuality = 13.200001, SaturationRatio = 1.2 };
        public static readonly Food Mutton = new Food { Id = 980, DisplayName = "Raw Mutton", Name = "mutton", StackSize = 64, FoodPoints = 2, Saturation = 1.2, EffectiveQuality = 3.2, SaturationRatio = 0.6 };
        public static readonly Food PoisonousPotato = new Food { Id = 950, DisplayName = "Poisonous Potato", Name = "poisonous_potato", StackSize = 64, FoodPoints = 2, Saturation = 1.2, EffectiveQuality = 3.2, SaturationRatio = 0.6 };
        public static readonly Food Porkchop = new Food { Id = 763, DisplayName = "Raw Porkchop", Name = "porkchop", StackSize = 64, FoodPoints = 3, Saturation = 1.8000001, EffectiveQuality = 4.8, SaturationRatio = 0.6 };
        public static readonly Food Potato = new Food { Id = 948, DisplayName = "Potato", Name = "potato", StackSize = 64, FoodPoints = 1, Saturation = 0.6, EffectiveQuality = 1.6, SaturationRatio = 0.6 };
        public static readonly Food Pufferfish = new Food { Id = 804, DisplayName = "Pufferfish", Name = "pufferfish", StackSize = 64, FoodPoints = 1, Saturation = 0.2, EffectiveQuality = 1.2, SaturationRatio = 0.2 };
        public static readonly Food PumpkinPie = new Food { Id = 960, DisplayName = "Pumpkin Pie", Name = "pumpkin_pie", StackSize = 64, FoodPoints = 8, Saturation = 4.8, EffectiveQuality = 12.8, SaturationRatio = 0.6 };
        public static readonly Food Rabbit = new Food { Id = 967, DisplayName = "Raw Rabbit", Name = "rabbit", StackSize = 64, FoodPoints = 3, Saturation = 1.8000001, EffectiveQuality = 4.8, SaturationRatio = 0.6 };
        public static readonly Food RabbitStew = new Food { Id = 969, DisplayName = "Rabbit Stew", Name = "rabbit_stew", StackSize = 1, FoodPoints = 10, Saturation = 12, EffectiveQuality = 22, SaturationRatio = 1.2 };
        public static readonly Food RottenFlesh = new Food { Id = 857, DisplayName = "Rotten Flesh", Name = "rotten_flesh", StackSize = 64, FoodPoints = 4, Saturation = 0.8, EffectiveQuality = 4.8, SaturationRatio = 0.2 };
        public static readonly Food Salmon = new Food { Id = 802, DisplayName = "Raw Salmon", Name = "salmon", StackSize = 64, FoodPoints = 2, Saturation = 0.4, EffectiveQuality = 2.4, SaturationRatio = 0.2 };
        public static readonly Food SpiderEye = new Food { Id = 865, DisplayName = "Spider Eye", Name = "spider_eye", StackSize = 64, FoodPoints = 2, Saturation = 3.2, EffectiveQuality = 5.2, SaturationRatio = 1.6 };
        public static readonly Food SuspiciousStew = new Food { Id = 1033, DisplayName = "Suspicious Stew", Name = "suspicious_stew", StackSize = 1, FoodPoints = 6, Saturation = 7.2000003, EffectiveQuality = 13.200001, SaturationRatio = 1.2 };
        public static readonly Food SweetBerries = new Food { Id = 1053, DisplayName = "Sweet Berries", Name = "sweet_berries", StackSize = 64, FoodPoints = 2, Saturation = 0.4, EffectiveQuality = 2.4, SaturationRatio = 0.2 };
        public static readonly Food TropicalFish = new Food { Id = 803, DisplayName = "Tropical Fish", Name = "tropical_fish", StackSize = 64, FoodPoints = 1, Saturation = 0.2, EffectiveQuality = 1.2, SaturationRatio = 0.2 };
        
        public static readonly Food[] All = { Apple, BakedPotato, Beef, Beetroot, BeetrootSoup, Bread, Carrot, Chicken, ChorusFruit, Cod, CookedBeef, CookedChicken, CookedCod, CookedMutton, CookedPorkchop, CookedRabbit, CookedSalmon, Cookie, DriedKelp, EnchantedGoldenApple, GlowBerries, GoldenApple, GoldenCarrot, HoneyBottle, MelonSlice, MushroomStew, Mutton, PoisonousPotato, Porkchop, Potato, Pufferfish, PumpkinPie, Rabbit, RabbitStew, RottenFlesh, Salmon, SpiderEye, SuspiciousStew, SweetBerries, TropicalFish };
    }
}